version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: komunitas-app
    restart: unless-stopped
    working_dir: /var/www/html
    volumes:
      - .:/var/www/html
    networks:
      - komunitas-network

  db:
    image: mysql:8.0
    container_name: komunitas-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: komunitas
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    networks:
      - komunitas-network

  webserver:
    image: nginx:alpine
    container_name: komunitas-webserver
    restart: unless-stopped
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
      - ./docker/nginx:/etc/nginx/conf.d
    networks:
      - komunitas-network

networks:
  komunitas-network:
    driver: bridge